### PR TITLE
Update travis nodejs version to 12

### PR DESCRIPTION
**Pull request by jkyberneees**
Updating Travis Nodejs version to 12. 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jkyberneees** [comment]
Hi @yohay-ma @mcollina in the context of the latest changes on undici error code, I just noticed that tests does not pass on  Nodejs v12, neither v14.

However tests passed green on pipeline for v10. See details: https://travis-ci.com/github/fastify/fast-proxy/builds/175879591
Any idea about this issue? Can you confirm this on your side as well?

Regards

**Comment by yohay-ma** [comment]
checking...

**Comment by yohayg** [comment]
@jkyberneees I see that undici is returning `UND_ERR_CONTENT_LENGTH_MISMATCH`
I'll check what is causing this

**Comment by yohayg** [comment]
@jkyberneees when I comment out this line everything works:

```
if (req.method === 'GET' || req.method === 'HEAD') {
        // headers['content-length'] = 0
      } else {
```

investigating...

**Comment by yohayg** [comment]
@jkyberneees  https://github.com/fastify/fast-proxy/pull/39

**Pull request merged**
