### PR TITLE
fix unit tests, replace pem with self-cert

### PR DESCRIPTION
**Pull request by Uzlopak**
We dont need to make big changes, to get the unit tests running again. Created a RSA private key and just supply it to pem, avoiding to make big refactoring.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
strange. locally it runs?!

**Comment by Uzlopak** [comment]
OK, replaced pem with self-cert. First replaced it with selfsigned, but then I realized that self-cert is made by @jsumners so I use that instead.

**Comment by jsumners** [comment]
For what it's worth, I don't care which one is used as long as it works. But I was planning to point out https://github.com/fastify/fastify/pull/3711 as the way to go about it.

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by Uzlopak** [comment]
Thank you.

**Review by Eomm — COMMENTED** [review]
Top!

**Pull request merged**
