### PR TITLE
Refactor benchmarks

### PR DESCRIPTION
**Pull request by jkyberneees**
Changes:
- We are externalising/updating the benchmarks into an independent project:  https://github.com/jkyberneees/nodejs-proxy-benchmarks
- Fixing undici tests. 
- Adding Node.js v10 and v14 to CI tests.

Issue ref: https://github.com/fastify/fast-proxy/issues/41

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jkyberneees** [comment]
Hi @mcollina, I may kindly ask for your support here. The tests are now failing because of `undici` on:
```js
// lib/request.js
 } else if (
            key.length === 10 &&
            key.toLowerCase() === 'connection'
          ) {
            throw new InvalidArgumentError('invalid connection header')
```

It fails both in MacOS and Linux, did we missed something here regarding `undici` upgrades?

Regards

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jkyberneees** [comment]
> Hi @mcollina, may I kindly ask for your support here. The `undici` tests are now failing because:
> 
> ```js
> // lib/request.js
>  } else if (
>             key.length === 10 &&
>             key.toLowerCase() === 'connection'
>           ) {
>             throw new InvalidArgumentError('invalid connection header')
> ```
> 
> It fails both in MacOS and Linux, did we missed something here regarding `undici` upgrades?
> 
> Regards

Just found that we now require to delete the `connection` header when using `undici`.

**Comment by jkyberneees** [comment]
The build still fails for v12(https://github.com/fastify/fast-proxy/pull/43/checks?check_run_id=1519648114), I assume this is a bug in the Node.js  release. However, It successfully passes for v10 and v14.

I am proceeding to merge of this PR.

**Pull request merged**
